### ISSUE TITLE
Rewrite test module

### ISSUE THREAD

**Issue by thomas-maschler** [ucd-cws/arcpy_metadata#12]
rewrite test module to do some actual testing.

**Comment by nickrsan** [comment]
Converted the test module today to use the current style after you added the property decorators, etc, so it actually runs for the tests that function. The layer file test fails, but I'll file a separate bug for that.

**Comment by thomas-maschler** [comment]
Added some actual tests to the test module which first write values to metadata. After saving them, values in metadata file are compared to inserted values.
This works fine.

There are some open issues
- I cannot delete the file geodatabase due to existing locks. This seems to be cause by an arcpy process. I will report this to ESRI as a bug.
- File Identifieres for feature classes get deleted on import. I also cannot control this
- Something is wrong for raster datasets, need to dig deeper.

All of this doesn't seem to be related to the new test routines but rather to the module itself. will add it as separate tickets
