### ISSUE TITLE
Merge v0.4?

### ISSUE THREAD

**Issue by thomas-maschler** [ucd-cws/arcpy_metadata#15]
Hey Nick,

would you feel comfortable if I merge my current pull request into your repo?
Latest changes are not backwards compatible and the way you interact with the API a little bit different, but way easier.

It will also be much easier to add new items if needed.

I updated the documentation on our current fork
https://github.com/wri/arcpy_metadata

Thomas

**Comment by nickrsan** [comment]
Hi Thomas,

Yes, I feel very comfortable with that.. Sorry about that. I saw that today too, when I responded to the other issue and thought "oh crap, I need to do that!" I'm slammed this week, but if you do the merge, I'll update the package on PyPI next week and make sure to add a notice that it has breaking changes compared to previous versions. Sorry for having this linger so long.

**Comment by thomas-maschler** [comment]
Done

**Comment by nickrsan** [comment]
Wonderful - thank you - I'm really excited about this set of changes, so thank you for all of it!

**Comment by thomas-maschler** [comment]
Yeah, we use it a lot for our project. It becomes very handy. We build a whole web API around it, update our metadata using a webform and sync it with files on our server and on ArcGIS online.

**Comment by nickrsan** [comment]
That's a great way to use it - our infrastructure isn't quite that sophisticated yet :). My deadline schedule changed and I was able to update it on PyPI today, so it's now distributing 0.4.2 as well.

**Comment by thomas-maschler** [comment]
nice!

**Comment by StephNelsonMTA** [comment]
On a semi-related note, I found that I couldn’t successfully scrape for ‘tags’ with the prior version – has that been fixed?

**Comment by thomas-maschler** [comment]
sure you can simply overwrite the current item

metadata.tags = ["foo"]
t = metadata.tags
print t
>>> ["foo"]

metadata.tags = metadata.tags + ["bar"]
t = metadata.tags
print t
>>> ["foo", "bar"]

metadata.tags = []
t = metadata.tags
print t
>>> []

**Comment by StephNelsonMTA** [comment]
Thanks!
