### ISSUE TITLE
Coding problem

### ISSUE THREAD

**Issue by dragon881228** [ucd-cws/arcpy_metadata#19]
Hi, at first I would like to thanks for this very usefull tool in everyday issues. Unfortunately there are problems when using this tool for migrate, or multiple set of metadata when strings with metadata information contains symbols in different coding (for example ANSI1250 and symbols like "č", "ž", "é". etc.

Is there any solution for this problem?

Thank you very much!

**Comment by thomas-maschler** [comment]
The tool should already support unicode. I tested it using special characters from the French alphabet.
Can you send a sample metadata file you are trying to work on?

**Comment by dragon881228** [comment]
I'm sorry, it was my mistake. Unfortunatelly I forgot transfer variable with string in ANSI1250 to unicode. So it works now.
