### ISSUE TITLE
Metadata values not available

### ISSUE THREAD

**Issue by gpopulis** [ucd-cws/arcpy_metadata#2]
Using ArcMap version 10.3.0.4322
Windows 7 Enterprise version 6.1.7601 SP1 Build 7601
>>> md.__version__
'0.2.5'
------------------------------------

I am unable to pull the values from the metadata items through the library functions.  I have tried on .shp files as well as feature classes located in .gdbs.  Unsure of how to attach the data I'm using, but if you let me know how I would be happy to include it with this issue.  Below is from my ArcMap Python window
------------------------------------

>>> import arcpy_metadata as md
>>> data = md.MetadataEditor(r'C:\Temp\Example.shp')
Exporting metadata to temporary file c:\users\gpopulis\appdata\local\temp\arcd9b3\tmpmfsqivarcpy_metadata\pisces0metadata
>>> data.items
[<arcpy_metadata.MetadataAbstract object at 0x349DC250>, <arcpy_metadata.MetadataPurpose object at 0x349DC270>, <arcpy_metadata.MetadataTags object at 0x349DC2F0>, <arcpy_metadata.MetadataTitle object at 0x349DC490>]
>>> for item in data.items:
...     print item.name, item.value
...     
abstract 
purpose 
tags 
title

**Comment by nickrsan** [comment]
Thanks for filing the bug - I'll test a few things and get back to you. I'd thought data could be attached here, but looks like I was wrong. Feel free to upload the data to my Dropbox here: https://www.dropbox.com/request/BTkxzLAihAAhWOhALn5C - then I can verify the same issue on my end. Sorry for all of the trouble!

**Comment by nickrsan** [comment]
Marking this as closed for now - looks like the changes in 0.3.0 resolved the issue
