### ISSUE TITLE
ImportError: No module named 'version'

### ISSUE THREAD

**Issue by lilawren** [ucd-cws/arcpy_metadata#20]
Getting a ImportError: No module named 'version' error when running the tests.

May need to change arcpy_metadata\__init__.py

from arcpy_metadata.version import __author__
from arcpy_metadata.version import __version__

**Comment by nickrsan** [comment]
Thomas, in case you see this, this is related to us setting up arcpy_metadata on a Jenkins server we recently deployed and getting the import error. I'm going to correct and test it, and then we should have automated builds/tests (for the ones written) upon code changes.

**Comment by thomas-maschler** [comment]
Nice!

**Comment by nickrsan** [comment]
Pull request merged - thank you Lawrence!
