### ISSUE TITLE
suppress messages to console

### ISSUE THREAD

**Issue by dejames52** [ucd-cws/arcpy_metadata#30]
I would like to see an enhancement that would allow for suppression of the messages to the console for use of this module in a scripting environment. I have been able to control it by redirecting sys.stdout, but it would be a nice feature to have added to the MetadataEditor module as a flag.

**Comment by thomas-maschler** [comment]
with v0.5 you can now change log level when creating your editor. log levels higher than info (warning, error, critical) should not give and output
```
import arcpy_metadata as md
meta = md.MetadataEditor(r"path/to/my/dataset", loglevel="WARNING")
