### ISSUE TITLE
Unable to obtain information in the useLimit tag

### ISSUE THREAD

**Issue by dreamfool** [ucd-cws/arcpy_metadata#31]
I was not able to use arcpy.metadata object to access the limitation property - it came out empty.  I checked the XML structure and cannot see any reason why it wouldn't work.  

[CADASTRAL.PLSS_LN.txt](https://github.com/ucd-cws/arcpy_metadata/files/634431/CADASTRAL.PLSS_LN.txt)

**Comment by nickrsan** [comment]
Hi @dreamfool,

Thanks for reporting this - would you be able to provide a snippet of the code you used and at least a part of the original dataset? I see you attached the XML, but it will help us diagnose this if we can have at least the container feature class (the actual features themselves are not necessary if they're sensitive) that the XML came from. We'll look into this and see what we can find. Thanks!

**Comment by dreamfool** [comment]
Hi @nickrsan 

Thanks for the prompt response.  I have attached the Python function that I used to access the metadata object and a file GDB with this feature class in it (the original dataset was stored on SDE though).  I do notice I can access purpose property fine, but that seems about it.  

[get_metadata.zip](https://github.com/ucd-cws/arcpy_metadata/files/634531/get_metadata.zip)

**Comment by thomas-maschler** [comment]
Item is stored in the dataIdInfo/resConst path
there are several possible elements under this path (use limitations, legal limitations)

dataIdInfo/resConst/LegConsts/othConsts
dataIdInfo/resConst/Consts/useLimit

ArcCatalog creates two restConst elements while arcpy_metadata tries to write everything to the same restConst element.

**Comment by thomas-maschler** [comment]
fixed in 0.5-rc3
