### ISSUE TITLE
Dropdowns with code values?

### ISSUE THREAD

**Issue by MapZombie** [ucd-cws/arcpy_metadata#33]
I noticed in the code that all of the drop down types have been commented out.  And when trying these out **the coded values appear within the XML tag, which is incorrect and not read properly.**  Are there plans to fix this?  

I can help if I got some help on how the process of changing the tags works in the module.

**Comment by thomas-maschler** [comment]
Yes, this is still in the works.
Didn’t had a chance to work on this lately.

Latest branch currently lives here
https://github.com/wri/arcpy_metadata

which already supports adding nested groups. Drop down lists will be next.

**Comment by thomas-maschler** [comment]
Looking into the code again, I think I already worked on this

in the latest branch you can define drop down values like this
https://github.com/wri/arcpy_metadata/blob/master/arcpy_metadata/elements.py#L95-L99

I think there were still some loose ends, that's why i didn't merge it with the master branch yet. But I recently had other priorities and no time to finish it.

However, the code should work as is.

**Comment by MapZombie** [comment]
Awesome, I will test it out.  Thanks

**Comment by MapZombie** [comment]
Your code works for that particular dropdown.  I then tried this:
Added

`    "update_frequency": {
        "path": "dataIdInfo/resMaint/maintFreq/MaintFreqCd",
        "type": "attribute",
        "key": "value",
        "values": [("continual", "001"),
                   ("daily", "002"),
                   ("weekly", "003"),
                   ("fortnightly", "004"),
                   ("monthly", "005")]},`

and then ran script with:
`    metadata.update_frequency = ["weekly"]`

Result was the update frequency code value (MaintFreqCd) did not change to "003" or weekly in this case.  I'll keep digging, not sure why this would have a different result.

**Comment by thomas-maschler** [comment]
This is where i might have stopped

drop down list currently work for nested items (ie within the contacts or online resources) but not on simple objects

Here is where I add them to nested objects
https://github.com/wri/arcpy_metadata/blob/master/arcpy_metadata/metadata_constructors.py#L411-L424

the same logic needs to be implemented for the simple objects somewhere here
https://github.com/wri/arcpy_metadata/blob/master/arcpy_metadata/metadata_constructors.py#L97-L152

**Comment by MapZombie** [comment]
@thomas-maschler there seems to be quite a few moving parts to this code.  Would you be able to add this feature, as you know the code inside out?  Thanks.

**Comment by thomas-maschler** [comment]
Will work on this at one point but won’t be able to look at before mid-April

**Comment by nickrsan** [comment]
I like our API here a bit better (but naturally biased), but if you have an urgent need for this, it's possible this project supports that: https://github.com/consbio/gis-metadata-parser

**Comment by thomas-maschler** [comment]
fixed in 0.5-rc1
