### ISSUE TITLE
Attribute Error

### ISSUE THREAD

**Issue by adoezema** [ucd-cws/arcpy_metadata#43]
I keep on getting the following error:
   AttributeError: module 'arcpy' has no attribute 'XSLTransform_conversion'

any ideas?

**Comment by thomas-maschler** [comment]
Which version of arcpy do you use?
Python 2.7 32bit for ArcDesktop?
Python 2.7 64bit for ArcDesktop?
Python3.x 64 bit for Pro?

We use arcpy.XSLTransform_conversion to extract the metadata from file geo databases
This tool is not supported in 64bit. There is no way for us to access metadata for file geodatabases using these builds.
Try using the tool with the 32bit version

**Comment by adoezema** [comment]
Python3.x 64 bit for Pro.

Thanks for the quick response!

**Comment by darioromero** [comment]
> Which version of arcpy do you use?
> Python 2.7 32bit for ArcDesktop?
> Python 2.7 64bit for ArcDesktop?
> Python3.x 64 bit for Pro?
> 
> We use arcpy.XSLTransform_conversion to extract the metadata from file geo databases
> This tool is not supported in 64bit. There is no way for us to access metadata for file geodatabases using these builds.
> Try using the tool with the 32bit version

Is this resolved as of 2020 now? I am having the same issue with Python 3.6 64 bit for Pro. Please let me know. Thanks.

**Comment by nickrsan** [comment]
Hi Dario,

The resolution for this is that Esri has incorporated their own metadata module in ArcGIS Pro: https://pro.arcgis.com/en/pro-app/arcpy/metadata/metadata-class.htm

It doesn't incorporate support for ArcMap/Python 2.7 though, so if you need support for both, you'll need to make your code load and use the correct one based on which environment it's running in.
