### ISSUE TITLE
Upload 0.5.1 to pypi

### ISSUE THREAD

**Issue by thomas-maschler** [ucd-cws/arcpy_metadata#44]
Hi Nick, 
I noticed there was a bug with the logger. I fixed it, can you upload latest version to pypi?

Thanks

Thomas

**Comment by thomas-maschler** [comment]
Now 0.5.2

**Comment by nickrsan** [comment]
Apologies on the delay - was moving during this time period. Only holdup right now is that I need to migrate the upload to PyPI's new API. Once I do that, I'll get this uploaded - trying to do that today.

**Comment by nickrsan** [comment]
Uploaded at https://pypi.python.org/pypi/arcpy_metadata/0.5.2

For my own notes, I'm now using `twine` to handle the upload: https://pypi.python.org/pypi/twine - upgrading setuptools seemed like a bandaid (and was still running into errors).

**Comment by thomas-maschler** [comment]
Thanks!
