### ISSUE TITLE
write to text: metadata description has xml code 

### ISSUE THREAD

**Issue by UnderJollyRoger** [ucd-cws/arcpy_metadata#46]
I have a script that uses arcpy_metadata and writes the title, tags, purpose (summary) and description (abstract) to a text file. In general, it works great, but it looks like some XML code is being written along with the text. It's not causing any errors, only it interferes with the readability of the text file content. 
Here's a zip that has the script I created and the text file:
[Metadata2Txt.zip](https://github.com/ucd-cws/arcpy_metadata/files/1548449/Metadata2Txt.zip)

Thanks,
Jared

**Comment by thomas-maschler** [comment]
Hi Jared,

What you see is HTML code used to format the description text, not XML.
It is beyond the scope of arcpy_metadata to remove these additional tags. If you want to get rid of them you can use an additional library such as BeatifulSoup to remove them

```
from bs4 import BeautifulSoup
cleantext = BeautifulSoup(raw_html).text

```

Cheers,

Thomas

**Comment by UnderJollyRoger** [comment]
Sounds Good. Thanks Thomas.

**Comment by UnderJollyRoger** [comment]
Hi Thomas,

I was wondering if you knew of any specific help pages related to using BeautifulSoup to remove these HTML tags from the text file? 

Thanks in advance.

**Comment by StephNelsonMTA** [comment]
I use the attached script to scrape metadata from feature classes in our enterprise geodatabase and populate an Excel data dictionary.

This is of course customized for our environment and metadata standards, but you can see the BeautifulSoup library in action, which could help you get started. Namely, you want to use ‘html.parser’ to remove the HTML tags.

Good luck!
Steph


Steph A. Nelson | GIS Administrator/Developer
Senior IS Engineer, SFMTA Information Technology

**Comment by UnderJollyRoger** [comment]
@StephNelsonMTA 

Thanks Steph,

I'll take note of this for future reference. I actually found an alternative to BeautifulSoup that works quite nicely:
`from w3lib.html import remove_tags`
`abstract = metadata.abstract`
```
if abstract:
    new_abstract = remove_tags(abstract)
```
https://github.com/scrapy/w3lib

**Comment by StephNelsonMTA** [comment]
Gtk, thanks!
