### ISSUE TITLE
Replace getter and setter methods with @property decorator.

### ISSUE THREAD

**Issue by thomas-maschler** [ucd-cws/arcpy_metadata#6]
Instead of using Java-style getter and setter methods use Python's builtin getter/setter support through the @property decorator.

Afterwards, .get() and .set() methods will have to be marked as deprecated

**Comment by nickrsan** [comment]
Funny that you filed this today. I was thinking about that this morning too, and was wondering if I'd have time sometime soon to make that happen. I definitely agree that this needs to happen. Thanks Thomas.

**Comment by thomas-maschler** [comment]
fixed in v 0.4
