### ISSUE TITLE
Upgrades to support ArcGIS Pro

### ISSUE THREAD

**Issue by nickrsan** [ucd-cws/arcpy_metadata#61]
It looks like ArcGIS Pro now supports the required features to export metadata, and given that arcpy_metadata supports more features than arcpy.metadata in ArcGIS Pro, I think there's value in an upgrade of the library.

I'm working with more authoritative data pipelines again, so I'm going to try to work in an upgrade to ArcGIS Pro.

Expected tasks:
- [x] I think a clean break probably makes the most sense. I'm going to suggest a full version number upgrade and a warning message if we detect we're running in ArcMap to change code to use only version 0.5.3 or older. That way, we don't have to worry about keeping a code base that can run in both environments if ArcMap is end-of-life. Thinking about this more, maybe a final 0.5.4 to PyPI that explicitly says it's Python 2 only, and then we'll publish 1.x that only supports Python 3 so that the correct versions get pulled in.
- [ ] Upgrade project to use pyproject.toml
- [x] Remove dependency on six - optional, but we don't need it anymore
- [x] Change the methods used for exports and imports of XML metadata to be based on [arcpy.metadata](https://pro.arcgis.com/en/pro-app/latest/arcpy/metadata/metadata-class.htm#P_GUID-ED041163-664D-4982-9CBC-86A9F2332D11)
- [ ] It looks like the method Thomas implemented for removing GP history should still work, but the builtin ways to handle that changed, so we'll want to make sure that still works (is there a test for this?)
- [x] Ensure the test suite passes, check for any major missing items
- [ ] I'm considering a license change on the new version. I'd like to allow use, including commercial, but restrict a few uses. We'll see if I can find an appropriate license. Otherwise it'll stay MIT.
- [x] Update README
- [ ] It'd be good to also figure out where this repo should be homed. I don't work at CWS anymore and Thomas doesn't work at WRI. I'm doing work on this under the California Department of Technology, but I'm not sure if we can home the open source repo or not. I think we may want to keep this separate from each organization, either in a neutral space under my own account or in a new org (which seems like overkill). I'm likely to transfer it to my own account.
- [ ] I'd like to pair this with adding server dataset metadata editing. We can do a similar workflow using the ArcGIS API for Python to export - See #62. We may also consider bypassing this for now if we can get the tests passing for the rest in Pro, but we'll need it soon.
- [ ] That would also need to be added to documentation

**Comment by nickrsan** [comment]
Note that in 541b43d97420f79da9272072162c9b8d4932ee6d the code is working in ArcGIS Pro, though the test suite is failing

**Comment by nickrsan** [comment]
Something to confirm is that in Python 2.x it seems that XPath under lxml used 0-based indexing, but in 3.x it's using 1-based indexing. Making a change to the indexing behavior made the code run correctly in loading metadata from a feature class

**Comment by nickrsan** [comment]
OK - this is in a mostly good state with one single nagging issue that's a dealbreaker.

When reading the dataset from an existing file, MetadataObjectListConstructor does just fine, creating the right number of objects with the right values in their own memory. But if I use the `.new()` method, it creates not just a duplicate of the first item, but the values are actually the same in memory (that is, the values point to the first items values). So that's a problem.

I played with it a bit, and if I go delete arcpy_metadata's internal construction of the items, then do `.new()` again, it starts correctly adding the items back in order. So it seems like, somehow, when we *actually* want to go add a new item, it needs to add the element to the XML first, but that's not happening (why not? It used to?) - either I broke it during my upgrades or something about `lxml`'s updates, which have been significant, broke it.

Either way, it's kind of spaghetti to track down, and I've struggled to find resolution on this. We could release and just temporarily remove the `.new()` function there, but that will limit a lot of use cases. It'd be important to resolve.

I either need:
1. Some help from another person who can dig into this with me
2. To come back to this fresh where I can see what's going on - I can't spend any more time on it (I shouldn't have spent the time I did today on it)
3. To rewrite that specific behavior and document it better than it currently is. It's currently kind of a cluster of subclasses and contstructor classes that are the only subelement of a specific object. I don't think that much indirection is necessary, but I also think rewriting it risks a whole lot more. It'd be much nicer to document the behaviors that are currently there better instead, if I can understand them.

**Comment by nickrsan** [comment]
ArcGIS Pro support completed in 40c4db73dfa71b05b584dcb16e92548b9b61e938. I had made a few errors during prior updates that were the blockers.

Some of the other chores may still need to be done, but we could potentially publish version 1.0 and start getting some feedback without closing this issue.

**Comment by nickrsan** [comment]
Fully specified that 1.x is for Python 3 only, removed dependency on six, among other version change upgrades in 5e5a6210dd797606ca3f49536db0515abaf79efc

**Comment by nickrsan** [comment]
@thomas-maschler - I think your GitHub account may be gone (or private? not sure - your contributions don't show up in the graph anymore), but if you're still here and have any interest in reviewing this work upgrading arcpy_metadata to support ArcGIS Pro, let me know - I've been deep in code you added, and I think it's ready, but also wanted to mention you since you did so much on the ArcMap version.

**Comment by thomas-maschler** [comment]
Hey, not quite sure what happened to my settings but my account is still there. I don't have access to an ESRI license anymore d won't be able to test.
